"""Offline G4 reporting and POC decision, preserving all review labels."""
import csv,json,hashlib
from aggregate_v2_g4 import ROOT,G,B,read,write,sha,stats
s=read(G/'final_summary.json');f=read(G/'workflow_funnel.json');old=read(ROOT/'artifacts/evaluation_v2/f/summary.json')
def rows(n):
 with (B/n).open(encoding='utf-8',newline='') as stream:return list(csv.DictReader(stream))
rec=rows('v2_g4_retrieval_recovery.csv');pairs=rows('v2_g4_paired_comparison.csv');rm={x['query_id']:x for x in rec};pm={x['query_id']:x for x in pairs}
for name in ['v2_g4_cross_paper.csv','v2_g4_multi_hop.csv']:
 data=rows(name)
 for row in data:
  r=rm[row['query_id']];p=pm[row['query_id']]
  row.update(all_gold_top10=r['all_gold_top10'],all_gold_hybrid20=r['all_gold_top20'],supplemental_calls=r['supplemental_calls'],recovered_missing_gold=r['recovered_admitted'],all_missing_gold_recovered=r['all_missing_recovered'],A_incomplete_B_complete=p['A_incomplete_B_complete'],A_complete_B_incomplete=p['A_complete_B_incomplete'])
 with (B/name).open('w',encoding='utf-8',newline='') as out:
  w=csv.DictWriter(out,fieldnames=list(data[0]));w.writeheader();w.writerows(data)
summary_cross={}
for typ in ['cross_document','multi_hop']:
 data=[r for r in rec if r['query_type']==typ];ps=[r for r in pairs if r['query_type']==typ]
 summary_cross[typ]=dict(n=len(data),A_all_gold_top10=sum(r['all_gold_top10']=='True' for r in data),A_all_gold_top20=sum(r['all_gold_top20']=='True' for r in data),B_supplemental_tasks=sum(int(r['supplemental_calls'])>0 for r in data),B_queries_recovered_missing=sum(int(r['recovered_admitted'])>0 for r in data),B_all_missing_recovered=sum(r['all_missing_recovered']=='True' for r in data),A_incomplete_B_complete=sum(r['A_incomplete_B_complete']=='True' for r in ps),A_complete_B_incomplete=sum(r['A_complete_B_incomplete']=='True' for r in ps))
s['poc_category_diagnostics']=summary_cross
s['retrieval_ceiling_rates']={k:v/40 for k,v in s['retrieval_ceiling'].items()}
s['recovery']['global_returned_missing_units']=sum(int(r['recovered_global_returned']) for r in rec)
s['recovery']['initially_missing_queries']=sum(int(r['missing_before'])>0 for r in rec)
s['recovery']['initially_missing_still_limited_queries']=sum(int(r['missing_before'])>0 and int(r['all_required_still_missing'])>0 for r in rec)
s['review_vs_gold_caveat']='Exact Gold is a required-locator bookkeeping proxy, not an exhaustive list of semantically equivalent evidence. Review sufficiency can be higher; primary failure categories follow requested exact-Gold priority and are not causal verdicts.'
s['unsupported_distinction']={'R003':'3 contradictions / conflicts explicitly described','R019':'2 contradicted core claims explicitly described','R024':'1 material mischaracterization','R080':'1 mixed unsupported/contradicted claim; no forced split','frozen_total':7,'independent_human_review':False}
s['research_workflow_readiness']='PARTIAL';s['dominant_bottleneck']='MIXED';s['recommended_next_phase']='GENERATION_SYNTHESIS_OPTIMIZATION'
s['decision_reason']='Exact Gold ceiling and cross-paper recovery remain limited, while supplied evidence is judged sufficient for 32/40 A and 37/40 B-R. A has eight missed-opportunity abstentions; B-R has contradictions, omissions and two failures. Agent improves nine pairs but recovers missing exact Gold in only four; no single causal bottleneck is established. Prioritize evidence-use/synthesis as one optional next phase; do not implement it.'
config_names=['final_retrieval_manifest.json','final_chunking_config.json','final_dense_config.json','final_fusion_config.json','final_reranker_config.json','v2_g_workflow_benchmark.json','v2_g_generation_config.json','v2_g_track_a_context_config.json','v2_g_track_b_reconstructed_config.json','v2_g_runtime_provenance.json']
for p in [B/n for n in config_names]+[ROOT/'artifacts/evaluation_v2/f/test_run.json',ROOT/'artifacts/evaluation_v2/f/summary.json']:
 s['protected_hashes'][str(p.relative_to(ROOT)).replace(chr(92),'/')]=sha(p)
write(G/'final_summary.json',s)
can=['V2 retrieval was optimized on DEV and frozen before the single final retrieval TEST; no post-TEST retrieval tuning.','Saved V2-F results show positive reranker value on this TEST, not general superiority.','A and B-R use the same frozen 40-task benchmark; B-R uses frozen V2 retrieval in a reconstructed evaluation runtime.','Semantic judgments are MODEL_ASSISTED_SEMANTIC_REVIEW, with 80 frozen records and two workflow failures retained.','Observed paired outcomes: nine improvements, thirty unchanged, one regression.']
cannot=['Production readiness or historical production Agent performance.','Independent human-blind evaluation or human endorsement.','Reliable cross-paper retrieval / universal multi-hop success.','Statistically generalizable superiority from n=40 or causal benefit of supplemental retrieval.','Zero hallucination rate from Track A unsupported-count zero.']
close=dict(v2_status='COMPLETE',retrieval_optimization_status='COMPLETE',final_test_status='COMPLETE',workflow_poc_status='COMPLETE',review_method='MODEL_ASSISTED_SEMANTIC_REVIEW',historical_runtime_recovered=False,workflow_runtime='RECONSTRUCTED_EVALUATION_RUNTIME',track_a='FROZEN_CONTEXT',track_b='RECONSTRUCTED_RESEARCH_AGENT',research_workflow_readiness=s['research_workflow_readiness'],dominant_bottleneck=s['dominant_bottleneck'],recommended_next_phase=s['recommended_next_phase'],decision_reason=s['decision_reason'],all_frozen_config_hashes={n:sha(B/n) for n in config_names},final_retrieval_manifest_hash=sha(B/'final_retrieval_manifest.json'),benchmark_hash=sha(B/'v2_g_workflow_benchmark.json'),review_summary_hash=sha(G/'V2_G3_REVIEW_SUMMARY.json'),completed_review_hash=sha(G/'HUMAN_WORKFLOW_REVIEW_COMPLETED.md'),WHAT_WE_CAN_CLAIM=can,WHAT_WE_CANNOT_CLAIM=cannot,no_llm_calls=True,no_retrieval_calls=True,no_answer_regeneration=True,no_new_optimization_started=True)
write(G/'poc_closeout.json',close)

def table(headers,data):return '\n'.join(['| '+' | '.join(headers)+' |','| '+' | '.join(['---']*len(headers))+' |']+['| '+' | '.join(str(v).replace('|','/') for v in row)+' |' for row in data])
def percent(x):return f'{x*100:.2f}%'
def section(title,body):return '\n## '+title+'\n\n'+body+'\n'
report='# ResearchGraph V2 Final POC Report\n\nV2 and the workflow POC are COMPLETE; research workflow readiness is PARTIAL. This is a small descriptive evaluation of a RECONSTRUCTED_EVALUATION_RUNTIME, not production certification.\n'
report+=section('Review provenance and integrity','MODEL_ASSISTED_SEMANTIC_REVIEW. Not independent human-blind review; no later human adoption is assumed. Both supplied SHA-256 values matched. The 80 Markdown labels match the JSON judgments and expected totals: COMPLETE/PARTIAL/INCORRECT 51/18/11; evidence 69/9/2; citations 58/4/18; seven flagged claims across four items.\n\nAll 80 reviewed payloads match the original blinded material byte-for-byte after newline normalization and before label fields. The saved private mapping, query ID, exact rendered answer, parsed citation payload and evidence text establish 40 A + 40 B-R matches. Mapping hashes are in final_summary.json. No stylistic track inference. All inputs are preserved.')
report+=section('Track-level results',table(['Track','n','Complete','Partial','Incorrect','Complete rate','Evidence sufficient','Citation ALL','Flagged claims / answers','Complete + ALL'],[[m['track'],m['n'],m['COMPLETE'],m['PARTIAL'],m['INCORRECT'],percent(m['complete_rate']),m['evidence_SUFFICIENT'],m['citation_ALL'],str(m['unsupported_claims'])+'/'+str(m['answers_with_unsupported_claims']),str(m['correctly_cited_complete'])+' / '+percent(m['correctly_cited_complete_rate'])] for m in s['track_metrics']])+'\n\nFull partial/incorrect rates, all evidence/citation counts and denominators are in v2_g4_track_metrics.csv. Both workflow failures remain in B-R n=40.')
report+=section('Workflow status versus semantic correctness',table(['Runtime status','Semantic COMPLETE','PARTIAL','INCORRECT'],[[k,v['COMPLETE'],v['PARTIAL'],v['INCORRECT']] for k,v in s['workflow_semantic_crosstab'].items()])+'\n\nEight runtime-partial reports are semantically COMPLETE for the original question. A runtime completed state is not semantic correctness.')
report+=section('Paired comparison',table(['A → B-R','COMPLETE','PARTIAL','INCORRECT'],[[k,v['COMPLETE'],v['PARTIAL'],v['INCORRECT']] for k,v in s['paired_matrix'].items()])+f"\n\nImproved 9; unchanged 30; regressed 1. A incomplete → B complete: {s['A_incomplete_B_complete']}; A complete → B incomplete: {s['A_complete_B_incomplete']}. No significance or causal claim.")
report+=section('Query type breakdown — LOW_SAMPLE_DESCRIPTIVE',table(['Track','Type','n','Complete','Partial','Incorrect','Complete rate','Citation ALL rate','Flagged claims'],[[x['track'],x['query_type'],x['n'],x['COMPLETE'],x['PARTIAL'],x['INCORRECT'],percent(x['complete_rate']),percent(x['citation_ALL_rate']),x['unsupported_claims']] for x in s['query_type_metrics']]))
report+=section('Frozen retrieval ceiling',table(['Exclusive class','n','rate','A COMPLETE','A PARTIAL','A INCORRECT'],[[k,v,percent(v/40),*[s['ceiling_semantic_crosstab'][k][lab] for lab in ['COMPLETE','PARTIAL','INCORRECT']]] for k,v in s['retrieval_ceiling'].items()])+'\n\nTop20-only means not Top10-answerable. Inclusive all-Gold Hybrid20 count is 22/40. Three Top10-answerable tasks were not COMPLETE. Four tasks judged COMPLETE lack all exact Gold in Hybrid20: locator absence does not prove absence of equivalent semantic evidence. Fourteen incomplete A tasks are in the not-Top20 class; retrieval may bind, without causal certainty.')
report+=section('Agent Gold recovery','Before Agent = frozen A Final10; after Agent = union of actually admitted exact immutable locators across all calls, with no inherited A context. Global-returned coverage is separately recorded; it never counts as evidence sent to the model. A Gold unit is counted once, attributed to its first admitted phase.\n\n'+table(['Measure','Value'],[[k,v] for k,v in s['recovery'].items() if not isinstance(v,(dict,list)) and k!='definition'])+'\n\n'+table(['Recovered cohort','Complete','Partial','Incorrect'],[[k,*[s['recovery'][k][lab] for lab in ['COMPLETE','PARTIAL','INCORRECT']]] for k in ['recovered_semantics','all_recovered_semantics']])+'\n\nOnly one A-incomplete → B-complete pair also recovered missing exact Gold. This is ORCHESTRATION_RECOVERY_SUCCESS bookkeeping, not a causal estimate. B can lose Gold originally present in A because retrieval/context admission differ; those lost locators are retained in the recovery CSV.')
report+=section('Retrieval intensity and cost',table(['Per-task measure','Mean','Median','p95','Max'],[[k,*[round(v[x],3) for x in ['mean','median','p95','max']]] for k,v in s['intensity'].items() if isinstance(v,dict)])+'\n\n201 retrieval calls; 19/40 tasks triggered supplemental retrieval. Subqueries are recorded both as invocations and distinct query strings. p95 uses linear interpolation at (n−1)×0.95. Workflow latency units are ms. No missing timing/token data were obtained by rerunning tasks.')
report+=section('Supplemental versus no supplemental — observational',table(['Group','n','Complete rate','Partial rate','Incorrect rate','Paired improved','unchanged','regressed'],[[k,v['metrics']['n'],percent(v['metrics']['complete_rate']),percent(v['metrics']['partial_rate']),percent(v['metrics']['incorrect_rate']),v['paired'].get('B_R_IMPROVED',0),v['paired'].get('UNCHANGED',0),v['paired'].get('B_R_REGRESSED',0)] for k,v in s['supplemental_groups'].items()])+'\n\nCoverage-triggered groups differ in difficulty. These rates do not measure causal benefit or harm from supplemental retrieval.')
report+=section('Failure attribution',table(['Primary cause','A','B-R'],[[c,s['failure_counts']['A'][c],s['failure_counts']['B-R'][c]] for c in s['failure_counts']['A']])+'\n\nExactly one primary cause per incomplete answer, following the requested exact-Gold precedence. This is proxy-based diagnosis: review-sufficient / Gold-absent conflicts and full reviewer notes remain in the CSV. Lower-priority synthesis problems are not erased: seven frozen flagged claims remain recorded separately. V2Q048 is a validator rejection (not a transport failure); V2Q075 is timeout/network failure. Both use the requested WORKFLOW_TECHNICAL_FAILURE bucket, with their distinction preserved.')
report+=section('Workflow funnels', 'Counts below are marginal stage counts (denominator 40); they may increase because review sufficiency and exact Gold availability are different constructs. Strict cumulative-intersection counts are also shown, preventing an invalid monotonic-funnel claim.\n\n'+ '\n\n'.join('### '+t+'\n\n'+table(['Stage','Marginal n','Marginal %','Cumulative n','Cumulative %'],[[x['stage'],x['count'],percent(x['rate']),x['cumulative_count'],percent(x['cumulative_rate'])] for x in stages]) for t,stages in f['tracks'].items()))
report+=section('Cross-document and multi-hop POC','LOW_SAMPLE_DESCRIPTIVE: cross_document n=8; multi_hop n=6 per track.\n\n'+table(['Category','Track','FULL','PARTIAL','FAIL'],[[cat,t,*[s[cat][t].get(x,0) for x in ['FULL','PARTIAL','FAIL']]] for cat in ['cross_document','multi_hop'] for t in ['A','B-R']])+'\n\n'+table(['Category','Diagnostic','Count'],[[cat,k,v] for cat,d in summary_cross.items() for k,v in d.items()])+'\n\nCross-paper FULL requires COMPLETE + citations ALL + all scoped papers actually cited; a one-paper answer cannot qualify. Multi-hop FULL additionally requires all exact frozen Gold available in the track context. Other non-INCORRECT / nonfailed outputs are conservative PARTIAL, not FULL. B-R has four semantic COMPLETE multi-hop answers but only one satisfies the stricter exact-Gold FULL rule; do not conflate the two.')
report+=section('Abstention',table(['Track','Safe','Missed opportunity'],[[t,v['counts'].get('SAFE_ABSTENTION',0),v['counts'].get('MISSED_OPPORTUNITY_ABSTENTION',0)] for t,v in s['abstention'].items()])+'\n\nA counts whole-answer abstention. B-R counts validated reports containing any insufficient-evidence cell, including cells broader than the original question. A sufficient G3 evidence label or full exact-Gold availability marks missed opportunity; otherwise safe under the frozen evidence review. Individual records retain both bases. This does not rejudge G3 labels or treat all abstentions as safety failures.')
report+=section('Unsupported / contradicted claims and citations',table(['Track','Query','Review ID','Frozen count','Original distinction'],[[t,x['query_id'],x['review_item_id'],x['count'],s['unsupported_distinction'][x['review_item_id']]] for t,items in s['unsupported_claims'].items() for x in items])+'\n\nFive issues are explicitly contradictions/conflicts (R003, R019); R024 is a mischaracterization and R080 has mixed unsupported/contradicted wording. Counts are unchanged and no new per-claim labels are invented. Zero flagged claims for A is not a zero-hallucination-rate claim.\n\n'+table(['Track','ALL','PARTIAL','NONE','COMPLETE+ALL','COMPLETE+PARTIAL/NONE','PARTIAL+ALL'],[[t,*[d[k] for k in ['ALL','PARTIAL','NONE','complete_all','complete_partial_or_none','partial_all']]] for t,d in s['citation_quality'].items()]))
rr=old['TEST_metrics'];report+=section('POC readiness and next phase','Readiness: **PARTIAL**. Dominant bottleneck: **MIXED**.\n\n'+s['decision_reason']+'\n\nPrimary recommendation: **GENERATION_SYNTHESIS_OPTIMIZATION**, with no implementation in this closeout. This prioritizes supplied-evidence use and incorrect insufficiency/contradiction behavior; it does not deny the unresolved cross-paper candidate-coverage limitation. No retroactive numeric pass threshold is introduced.')
report+=section('WHAT WE CAN CLAIM','\n'.join('- '+x for x in can)+f"\n\nSaved final TEST Hybrid R@10 = {rr['hybrid']['metrics']['R@10']:.4f}; reranked R@10 = {rr['reranked']['metrics']['R@10']:.4f}. This is retrieval ranking value on that fixed TEST, not proof of semantic or production superiority.")
report+=section('WHAT WE CANNOT CLAIM','\n'.join('- '+x for x in cannot))
report+=section('Reproduction and artifacts','Run only `python backend/scripts/aggregate_v2_g4.py`, followed by `python backend/scripts/report_v2_g4.py`, then offline integrity tests. These use only standard-library file processing and saved results. No LLM, retriever, model encoding, label edits or answer regeneration. Seven CSVs in benchmarks/real_research/v2 and final_summary.json, workflow_funnel.json, poc_closeout.json in artifacts/evaluation_v2/g contain complete machine-readable results and hashes. V2 COMPLETE; POC COMPLETE; no further optimization started.')
(ROOT/'docs/V2_POC_FINAL_REPORT.md').write_text(report,encoding='utf-8')
p=ROOT/'docs/evaluation_v2_research_workflow.md';text=p.read_text(encoding='utf-8');marker='\n## V2-G4 Final Offline Aggregation'
text=text.split(marker)[0]+marker+'\n\nV2/POC COMPLETE; readiness PARTIAL; bottleneck MIXED. Review provenance: **MODEL_ASSISTED_SEMANTIC_REVIEW**, not independent human-blind review. All 80 frozen labels passed checksum and deterministic mapping. A COMPLETE 23/40; B-R COMPLETE 28/40; paired improved/unchanged/regressed 9/30/1. Failures remain in denominator 40. No labels, answers, retrieval or configs were changed.\n\nFull diagnostics, exact-Gold limitations, abstention definitions, and claim boundaries: [V2 POC Final Report](V2_POC_FINAL_REPORT.md). Recommended optional next phase: GENERATION_SYNTHESIS_OPTIMIZATION; not started.\n'
p.write_text(text,encoding='utf-8')
print('G4 report and POC closeout written')
