"""Render completed DEV candidate experiments without rerunning retrieval."""
import argparse,csv,hashlib,json
from pathlib import Path
p=Path(__file__).resolve().parents[2]/'benchmarks/real_research/v2';out=p/'results'
a=json.loads((out/'v2a_candidates_v2.json').read_text());baseline=json.loads((out/'dev_baseline_frozen_gold.json').read_text())
parser=argparse.ArgumentParser();parser.add_argument('--selected',required=True);args=parser.parse_args()
d=[json.loads(f.read_text()) for f in sorted(out.glob('v2a-D-*.json'))];assert len(d)==8
selected=next(e for e in d if e['id']==args.selected)
assert all(e['status']=='COMPLETE' and e['tracks']['global']['overall']['n']==35 for e in d)
fmt=lambda v: '-' if v is None else f'{100*v:.2f}'
metric=lambda e,t='global':e['tracks'][t]['overall']
xmetric=lambda e,t='global':e['tracks'][t]['cross_document']
lines=['# V2-A Candidate Generation','','Status: COMPLETE. All policies remain experiment-only; production defaults and public APIs unchanged.','','## Frozen Baseline','','Corpus: 30 papers / 432 pages / 3837 chunks. DEV 35 human-reviewed queries; TEST 40 untouched.','DEV SHA-256: `'+a['dev_hash']+'`','TEST SHA-256: `'+a['test_hash']+'`','Baseline: dev_baseline_frozen_gold.json. Annotation corrections are excluded from algorithm comparisons.','','|Global baseline|R@10|MRR@10|CR@20|CR@50|E2E p50 ms|E2E p95 ms|','|---|---:|---:|---:|---:|---:|---:|']
for mode,m in baseline['tracks']['global']['modes'].items():lines += [f"|{mode}|{fmt(m['Recall@10'])}|{m['MRR@10']:.4f}|{fmt(m['Candidate Recall@20'])}|{fmt(m['Candidate Recall@50'])}|{m['P50 Latency']:.3f}|{m['P95 Latency']:.3f}|"]
lines+=['','## Current Candidate Flow','','Production BM25 requests 200 from BM25Index, then authoritative active-version validation. Dense requests min(200,max(2*top_k,dense_top_k)); validated rows are not sliced back to top_k. Thus frozen baseline search(top_k=100) sends up to 200 candidates PER SOURCE to fusion, not 100.','FusionRanker deduplicates by chunk occurrence ID; equal source RRF contributions use k=60. Fusion returns up to600, followed by active-version/scope validation, then [:top_k]. Baseline retains Top100; its scorer takes Top20 and returns Top10. Public rerank=True recursively searches with top_k=20, meaning Dense initially requests40 (default dense_top_k=8), BM25 requests200; that path is not identical to the benchmark acquisition path.','No BM25-prefix preservation is guaranteed by RRF. Two-source agreement can displace BM25-only high-ranked evidence.','Raw Union@K means each source Top-K union, up to2K. It is not an equal-budget comparison with RRF@K.','','### Experiment A: RRF output depth (fixed 200/200 source depth)','','|Track|Pool|Candidate recall|Cross-document candidate recall|R@10|MRR@10|','|---|---:|---:|---:|---:|---:|']
for t in ['global','scoped']:
 for e in a['experiments']:
  if e['id'].startswith('v2a-A'):
   m=metric(e,t);x=xmetric(e,t);lines += [f"|{t}|{e['budget']}|{fmt(m['candidate_recall'])}|{fmt(x['candidate_recall'])}|{fmt(m['Recall@10'])}|{m['MRR@10']:.4f}|"]
lines+=['','## Retrieval Depth Analysis','','B is coordinate analysis, not a16-point grid. Every source depth was actually fetched/warmed/timed; Dense overfetch is explicitly capped BEFORE fusion. Choosing a source depth cannot be confused with post-RRF top_k.','Coordinate selection rule: maximize mean Global CR@20/@30/@50, then cross-document coverage, then smaller depth. Choice: '+str(a['coordinate_choice']), 'Individual recall below uses the full source depth; union uses all supplied candidates and has unequal pool sizes.','']
for t in ['global','scoped']:
 lines += ['### '+t,'','|Sweep|BM25 k|Dense k|BM25 individual CR|Dense individual CR|Full union CR|RRF CR20|RRF CR30|RRF CR50|Retrieval p50 ms|Retrieval p95 ms|','|'+'---|'*11]
 groups={}
 for e in a['experiments']:
  if e['id'].startswith('v2a-B'):groups.setdefault(e['id'].rsplit('-m',1)[0],{})[e['budget']]=e
 for label,es in groups.items():
  e=es[50];m=metric(e,t);diag=e['tracks'][t]['source_diagnostics']
  lines += [f"|{label}|{e['bm25_k']}|{e['dense_k']}|{fmt(diag['bm25_recall'])}|{fmt(diag['dense_recall'])}|{fmt(diag['full_union_recall'])}|{fmt(metric(es[20],t)['candidate_recall'])}|{fmt(metric(es[30],t)['candidate_recall'])}|{fmt(m['candidate_recall'])}|{m['retrieval_p50']:.3f}|{m['retrieval_p95']:.3f}|"]
lines+=['','## Equal-Budget Candidate Comparison','','Each row compares actual candidate membership at the requested budget; M greater than the configured pool is reported unavailable, not as saturated CR@M. Single-source pools fetch100 (enough for M50), current RRF uses200/200, protected union uses coordinate-selected40/100.','']
for t in ['global','scoped']:
 lines+=['### '+t,'','|Policy|Budget|CR@budget|Actual size min/max|H@5|R@5|R@10|MRR@10|Retrieval p50 ms|','|'+'---|'*9]
 for e in a['experiments']:
  if e['id'].startswith('v2a-C2'):
   m=metric(e,t);sz=m['pool_size'];lines += [f"|{e['policy']}|{e['budget']}|{fmt(m['candidate_recall'])}|{sz['min']}/{sz['max']}|{fmt(m['HitRate@5'])}|{fmt(m['Recall@5'])}|{fmt(m['Recall@10'])}|{m['MRR@10']:.4f}|{m['retrieval_p50']:.3f}|"]
lines+=['','## Protected Union Experiment','','Protect floor(M/2) from each source, deduplicate, fill remaining slots from unchanged RRF order, then order chosen membership by RRF. No weights, model, or scoring normalization change.','At Global budgets20/30/50 protected CR is52.62/62.62/65.71%, versus BM25-only60.00/64.29/71.43%. Protected union is not selected; it remains only as a reproducible ablation, with no production adoption.','Original C budget50 BM25 erroneously retained40 due to coordinate source depth. That record is preserved as INVALID_EQUAL_BUDGET and excluded from selection. C2 fixes source capacity and recomputes only deterministic construction on already collected source results. See v2a_candidates.status.json and ledger.','','## Cross-document Analysis','','All candidate experiments also store cross-document metrics in their JSON. Below is the equal-budget source comparison; no scoped metric was used to choose parameters.','','|Track|Policy|Budget|CR@budget|R@10|MRR@10|','|'+'---|'*6]
for t in ['global','scoped']:
 for e in a['experiments']:
  if e['id'].startswith('v2a-C2'):
   x=xmetric(e,t);lines += [f"|{t}|{e['policy']}|{e['budget']}|{fmt(x['candidate_recall'])}|{fmt(x['Recall@10'])}|{x['MRR@10']:.4f}|"]
lines+=['','## Rerank Depth Trade-off','','Global primary track; current RRF vs candidate-source winner. Each depth has its own one-query warmup then35 timed queries. No LLM or external model service. Scoped A/B/C reported separately; no scoped D grid.','','|Policy|Depth|Candidate recall|Cross candidate recall|R@10|MRR@10|Cross R@10|Retrieval p50/p95 ms|Reranker p50/p95 ms|E2E p50/p95 ms|','|'+'---|'*10]
for e in d:
 m=metric(e);x=xmetric(e);lines += [f"|{e['policy']}|{e['budget']}|{fmt(m['candidate_recall'])}|{fmt(x['candidate_recall'])}|{fmt(m['Recall@10'])}|{m['MRR@10']:.4f}|{fmt(x['Recall@10'])}|{m['retrieval_p50']:.3f}/{m['retrieval_p95']:.3f}|{m['reranker_p50']:.3f}/{m['reranker_p95']:.3f}|{m['e2e_p50']:.3f}/{m['e2e_p95']:.3f}|"]
lines+=['','## Latency','','Source retrieval is measured separately per retriever/depth/track after warmup. Hybrid retrieval-only time sums the measured source paths and construction time. Reranker-only is timed fresh per query/depth. E2E sums per-query retrieval and reranker times, then takes percentiles; it is not the sum of percentiles and not one contiguous HTTP request. SQL validation/serialization work differs slightly from the original production runner; latency comparisons are diagnostic, not a strict service SLO claim.','Embedding cold load (ms): '+str(a['embedding_cold_ms']), 'Reranker cold loads across initial/resumed sessions (ms): '+str(sorted({e['reranker_cold_ms'] for e in d}))+'. Model loading excluded from all steady-state metrics. BM25 Top50 completed after a process interruption on the following session; seven completed groups were preserved without reruns.','','## Selected DEV Configuration','','```json',json.dumps({**{k:selected[k] for k in ['id','policy','bm25_k','budget','rerank_k']},'dense_k':0 if selected['policy']=='bm25' else selected['dense_k']},indent=2),'```','','Production defaults: UNCHANGED. This selection is DEV-only and requires a later separate TEST evaluation before a generalization claim.','','## Why Selected','',*json.loads((out/'v2a_selection.json').read_text())['rationale'],'','## Limitations','','-35 DEV questions, only7 cross-document cases; results are observations, not significance/generalization claims.','- No TEST evaluation or ranking inspection.','- Source selection and depth tuned on DEV, with fixed reviewed Gold; no annotation changes.','- Scoped corpus filtering provides extra information and is not comparable to global search difficulty.','- Raw union versus RRF has different candidate budgets; equal-budget C2 is the fair pool-size comparison.','- Reranking cannot recover evidence outside its candidate pool.','- English queries still use fixed Chinese BGE; embedding changes deferred to V2-B.','- Protected-union membership is not necessarily nested across budgets; CR@M is computed for the actual constructed pool.','- All old/failed experiments retained; no best-seed reruns.','']
path=p.parents[2]/'docs/evaluation_v2_candidate_generation.md';path.write_text('\n'.join(lines),encoding='utf-8')
print(path)
