// @vitest-environment jsdom
import React from 'react';
import { beforeEach,afterEach,it,expect,vi } from 'vitest';
import { render,screen,fireEvent,cleanup,waitFor,within,act } from '@testing-library/react';
import { MemoryRouter,Routes,Route,Link } from 'react-router-dom';
import { readFileSync } from 'node:fs';
import AskWorkspace from '../pages/AskWorkspace';
import { libraryApi } from '../api/library';
import { askGroundedQuestion,citationEvidence } from '../api/qa';
import { ApiClientError } from '../api/errors';
vi.mock('../api/library',()=>({libraryApi:{documents:vi.fn()}}));
vi.mock('../api/qa',async original=>({...await original(),askGroundedQuestion:vi.fn()}));
const papers=[{id:1,title:'Ready One',status:'ready'},{id:2,title:'Ready Two',status:'ready'},{id:3,title:'Processing',status:'processing'}];
const citation=id=>({citation_id:`C${id}`,document_id:id,document_version_id:40+id,chunk_id:`chunk-${id}`,document_title:`Paper ${id}`,document:{version:3},page:7+id,section:`Section ${id}`,snippet:`Evidence ${id}`,source_reference:'C:/private/source.pdf'});
const answered=()=>({status:'answered',answer:'First fact [C1].\n\nSecond fact [C2].',citations:[citation(2),citation(1)],citation_validation:{valid:true},search:{results:[{text:'UNUSED RETRIEVAL CANDIDATE'}]}});
beforeEach(()=>{vi.resetAllMocks();window.matchMedia=vi.fn(q=>({matches:q.includes('min-width'),media:q,addListener:vi.fn(),removeListener:vi.fn(),addEventListener:vi.fn(),removeEventListener:vi.fn()}));const style=window.getComputedStyle.bind(window);vi.spyOn(window,'getComputedStyle').mockImplementation(el=>style(el));Object.defineProperty(document,'hidden',{configurable:true,value:false});libraryApi.documents.mockResolvedValue(papers);askGroundedQuestion.mockResolvedValue(answered());});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
async function mount(){render(<MemoryRouter><AskWorkspace/></MemoryRouter>);await waitFor(()=>expect(screen.getByRole('combobox').disabled).toBe(false));}
function ask(){fireEvent.change(screen.getByLabelText('Question'),{target:{value:'Explain evidence'}});fireEvent.click(screen.getByRole('button',{name:'Ask',exact:true}));}
async function choose(title){fireEvent.mouseDown(screen.getByRole('combobox'));fireEvent.click(await screen.findByText(title,{selector:'.ant-select-item-option-content'}));}
it('empty question disables button and guards keyboard submission',async()=>{await mount();expect(screen.getByRole('button',{name:'Ask',exact:true}).disabled).toBe(true);fireEvent.keyDown(screen.getByLabelText('Question'),{key:'Enter',ctrlKey:true});expect(screen.getByText('Enter a question.')).toBeTruthy();expect(askGroundedQuestion).not.toHaveBeenCalled();});
it.each([1,2])('submits %s selected ready documents',async count=>{await mount();await choose('Ready One');if(count===2)await choose('Ready Two');ask();await waitFor(()=>expect(askGroundedQuestion).toHaveBeenCalledWith({question:'Explain evidence',documentIds:count===1?[1]:[1,2]},expect.anything()));},15000);
it('ready-only selector and Ctrl Enter submission',async()=>{await mount();fireEvent.mouseDown(screen.getByRole('combobox'));await screen.findByText('Ready One',{selector:'.ant-select-item-option-content'});expect(screen.queryByText('Processing')).toBeNull();fireEvent.change(screen.getByLabelText('Question'),{target:{value:'Keyboard question'}});fireEvent.keyDown(screen.getByLabelText('Question'),{key:'Enter',ctrlKey:true});await waitFor(()=>expect(askGroundedQuestion).toHaveBeenCalledWith({question:'Keyboard question',documentIds:[]},expect.anything()));});
it('loading is honest and duplicate asks are blocked',async()=>{let resolve;askGroundedQuestion.mockReturnValue(new Promise(r=>resolve=r));await mount();ask();fireEvent.keyDown(screen.getByLabelText('Question'),{key:'Enter',metaKey:true});expect(screen.getByText('Generating grounded answer...')).toBeTruthy();expect(askGroundedQuestion).toHaveBeenCalledTimes(1);await act(async()=>resolve(answered()));});
it('answer safely renders paragraphs, binds shuffled citations by ID, switches exact evidence',async()=>{
 const data=answered();data.answer='<img src=x onerror=alert(1)> [C1].\n\nSecond [C2]. Unknown [C999].';askGroundedQuestion.mockResolvedValue(data);
 await mount();ask();await screen.findByRole('button',{name:'Open evidence C1'});expect(document.querySelector('.grounded-answer img')).toBeNull();expect(document.querySelectorAll('.grounded-answer p')).toHaveLength(2);expect(screen.queryByRole('button',{name:'Open evidence C999'})).toBeNull();expect(screen.queryByText('UNUSED RETRIEVAL CANDIDATE')).toBeNull();
 fireEvent.click(screen.getByRole('button',{name:'Open evidence C1'}));let panel=screen.getByRole('complementary');expect(within(panel).getByText('chunk-1')).toBeTruthy();expect(within(panel).getByText('41')).toBeTruthy();expect(within(panel).getByText('8')).toBeTruthy();expect(within(panel).getByText('3')).toBeTruthy();expect(within(panel).getByText('Section 1')).toBeTruthy();expect(within(panel).getByText('Evidence 1')).toBeTruthy();expect(panel.textContent).not.toContain('C:/private');
 fireEvent.click(screen.getByRole('button',{name:'Open evidence C2'}));panel=screen.getByRole('complementary');expect(within(panel).getByText('chunk-2')).toBeTruthy();expect(screen.getByRole('button',{name:'Open evidence C2'}).getAttribute('aria-pressed')).toBe('true');expect(askGroundedQuestion).toHaveBeenCalledTimes(1);
});
it('insufficient evidence never renders supplied answer or candidates',async()=>{askGroundedQuestion.mockResolvedValue({...answered(),status:'insufficient_evidence',answer:'UNTRUSTED FALLBACK'});await mount();ask();await screen.findByText('Insufficient evidence');expect(screen.queryByText('UNTRUSTED FALLBACK')).toBeNull();expect(screen.queryByRole('button',{name:'Open evidence C1'})).toBeNull();expect(screen.queryByRole('complementary')).toBeNull();});
it.each(['citation_validation_failed','llm_provider_error','llm_timeout','llm_network_error','llm_configuration_error','invalid_model_response','network_error','backend_unavailable','retrieval_error'])('failure %s preserves question without answer/retry',async code=>{askGroundedQuestion.mockRejectedValue(new ApiClientError(code,code==='backend_unavailable'?503:200));await mount();ask();await waitFor(()=>expect(screen.getByRole('button',{name:'Ask',exact:true}).disabled).toBe(false));expect(screen.getByLabelText('Question').value).toBe('Explain evidence');expect(document.querySelector('.grounded-answer')).toBeNull();expect(askGroundedQuestion).toHaveBeenCalledTimes(1);if(code==='citation_validation_failed')expect(screen.getByText('Answer not returned')).toBeTruthy();else if(code.startsWith('llm_')||code==='invalid_model_response')expect(screen.getByText('The answer could not be generated.')).toBeTruthy();else expect(screen.getByText(new ApiClientError(code).message)).toBeTruthy();});
it('new submission clears old answer and selected evidence',async()=>{await mount();ask();fireEvent.click(await screen.findByRole('button',{name:'Open evidence C1'}));let resolve;askGroundedQuestion.mockReturnValue(new Promise(r=>resolve=r));ask();expect(screen.queryByRole('complementary')).toBeNull();expect(document.querySelector('.grounded-answer')).toBeNull();await act(async()=>resolve(answered()));});
it('ready documents revalidate on focus and route re-entry',async()=>{
 let now=1000;vi.spyOn(Date,'now').mockImplementation(()=>now);
 render(<MemoryRouter initialEntries={['/ask']}><Link to="/away">Leave</Link><Link to="/ask">Return</Link><Routes><Route path="/ask" element={<AskWorkspace/>}/><Route path="/away" element={<p>Away</p>}/></Routes></MemoryRouter>);
 await waitFor(()=>expect(screen.getByRole('combobox').disabled).toBe(false));libraryApi.documents.mockResolvedValue([...papers,{id:4,title:'New ready paper',status:'ready'}]);now=3000;fireEvent.focus(window);await choose('New ready paper');expect(libraryApi.documents).toHaveBeenCalledTimes(2);fireEvent.click(screen.getByRole('link',{name:'Leave'}));fireEvent.click(screen.getByRole('link',{name:'Return'}));await waitFor(()=>expect(libraryApi.documents).toHaveBeenCalledTimes(3));
},15000);
it('QA reuses wrapping EvidencePanel without truncating the returned snippet',async()=>{
 const style=document.createElement('style');style.textContent=readFileSync('src/styles.css','utf8');document.head.append(style);
 try {const c=citation(1);c.document_title='LongTitle'.repeat(100);c.snippet='LongEvidence'.repeat(100);c.chunk_id='LongChunk'.repeat(100);askGroundedQuestion.mockResolvedValue({...answered(),citations:[c]});await mount();ask();fireEvent.click(await screen.findByRole('button',{name:'Open evidence C1'}));const panel=screen.getByRole('complementary');expect(within(panel).getByText(c.snippet).textContent).toBe(c.snippet);for(const el of [within(panel).getByText(c.snippet),within(panel).getByText(c.chunk_id),within(panel).getByRole('link').parentElement])expect(getComputedStyle(el).overflowWrap).toBe('anywhere');expect(citationEvidence(c).document_version_id).toBe(c.document_version_id);}finally{style.remove();}
},15000);
