// @vitest-environment jsdom
import React from 'react';
import { beforeEach,afterEach,it,expect,vi } from 'vitest';
import { render,screen,fireEvent,cleanup,waitFor,within,act } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { readFileSync } from 'node:fs';
import ResearchWorkspace from '../pages/ResearchWorkspace';
import { libraryApi } from '../api/library';
import { runResearchTask } from '../api/research';
import { ApiClientError } from '../api/errors';
vi.mock('../api/library',()=>({libraryApi:{documents:vi.fn()}}));
vi.mock('../api/research',()=>({runResearchTask:vi.fn()}));
const papers=[{id:1,title:'Paper One',status:'ready'},{id:2,title:'Paper Two',status:'ready'},{id:3,title:'Processing paper',status:'processing'}];
const citation=id=>({citation_id:`C${id}`,document_id:id,document_version_id:40+id,chunk_id:`chunk-${id}`,document_title:`Paper ${id}`,document:{version:3},page:7+id,section:`Section ${id}`,snippet:`Evidence ${id}`});
const response=(status='completed')=>({run_id:'run-123',status,citations:[citation(2),citation(1)],retry_count:1,errors:[],report:{summary:'Research summary [C1].',comparison:[{document_id:1,field:'method',value:'Method One [C1]',status:'supported'},{document_id:2,field:'method',value:'Method Two [C2]',status:'supported'},{document_id:1,field:'main_findings',value:'Finding One [C1]',status:'supported'}],limitations:['Limited evidence.']},coverage:{covered:[{document_id:1,field:'method'},{document_id:2,field:'method'},{document_id:1,field:'main_findings'}],missing:[{document_id:2,field:'main_findings'}]}});
beforeEach(()=>{vi.resetAllMocks();window.matchMedia=vi.fn(q=>({matches:q.includes('min-width'),media:q,addListener:vi.fn(),removeListener:vi.fn(),addEventListener:vi.fn(),removeEventListener:vi.fn()}));const style=window.getComputedStyle.bind(window);vi.spyOn(window,'getComputedStyle').mockImplementation(el=>style(el));Object.defineProperty(document,'hidden',{configurable:true,value:false});libraryApi.documents.mockResolvedValue(papers);runResearchTask.mockResolvedValue(response());});
afterEach(()=>{cleanup();vi.restoreAllMocks();});
async function mount(){render(<MemoryRouter><ResearchWorkspace/></MemoryRouter>);await waitFor(()=>expect(screen.getByRole('combobox').disabled).toBe(false));}
async function choose(title){fireEvent.mouseDown(screen.getByRole('combobox'));fireEvent.click(await screen.findByText(title,{selector:'.ant-select-item-option-content'}));}
async function setup(){await mount();await choose('Paper One');await choose('Paper Two');fireEvent.change(screen.getByLabelText('Research Question'),{target:{value:'Compare methods'}});}
function submit(){fireEvent.click(screen.getByRole('button',{name:'Run Research',exact:true}));}
it('ready selector and minimum scope prevent invalid request',async()=>{await mount();expect(screen.getByRole('button',{name:'Run Research'}).disabled).toBe(true);fireEvent.submit(screen.getByLabelText('Research Question').closest('form'));expect(screen.getByText('Select between two and ten ready papers.')).toBeTruthy();await choose('Paper One');expect(screen.queryByText('Processing paper')).toBeNull();submit();expect(runResearchTask).not.toHaveBeenCalled();},15000);
it('empty question does not submit',async()=>{await setup();fireEvent.change(screen.getByLabelText('Research Question'),{target:{value:'   '}});expect(screen.getByRole('button',{name:'Run Research'}).disabled).toBe(true);fireEvent.submit(screen.getByLabelText('Research Question').closest('form'));expect(screen.getByText('Enter a research question.')).toBeTruthy();expect(runResearchTask).not.toHaveBeenCalled();},15000);
it('valid request has exact scope and blocks duplicate submission while loading',async()=>{let resolve;runResearchTask.mockReturnValue(new Promise(r=>resolve=r));await setup();submit();fireEvent.submit(screen.getByLabelText('Research Question').closest('form'));expect(runResearchTask).toHaveBeenCalledTimes(1);expect(runResearchTask).toHaveBeenCalledWith({question:'Compare methods',documentIds:[1,2]},expect.anything());expect(screen.getByText('Executing bounded research workflow...')).toBeTruthy();expect(screen.getByLabelText('Research Question').value).toBe('Compare methods');await act(async()=>resolve(response()));},15000);
it.each(['completed','partial'])('%s report shows comparison, coverage, limitations and exact Citation',async status=>{
 runResearchTask.mockResolvedValue(response(status));await setup();submit();await screen.findByText(status==='partial'?'Partial Research Result':'Research Complete');
 expect(screen.getByText(/Research summary/)).toBeTruthy();expect(screen.getByText('3 / 4 research cells covered')).toBeTruthy();expect(screen.getByText('Limited evidence.')).toBeTruthy();expect(screen.getByText('Covered')).toBeTruthy();expect(screen.getByText('Missing')).toBeTruthy();
 const table=screen.getByRole('table');expect(within(table).getByText('Method')).toBeTruthy();expect(within(table).getByText('Main findings')).toBeTruthy();expect(within(table).getByText('Missing evidence')).toBeTruthy();expect(within(table).getAllByRole('columnheader')).toHaveLength(3);
 fireEvent.click(within(table).getByRole('button',{name:'Open evidence C2'}));const panel=screen.getByRole('complementary');expect(within(panel).getByText('chunk-2')).toBeTruthy();expect(within(panel).getByText('42')).toBeTruthy();expect(within(panel).getByText('9')).toBeTruthy();expect(within(panel).getByText('Section 2')).toBeTruthy();expect(within(panel).getByRole('link').getAttribute('href')).toBe('/library/2');expect(runResearchTask).toHaveBeenCalledTimes(1);
},20000);
it.each(['fact_document_mismatch','citation_validation_failed','llm_provider_error','research_budget_exceeded','budget_exceeded','tool_timeout','research_execution_failed'])('failed %s never displays supplied unvalidated report',async code=>{runResearchTask.mockResolvedValue({...response('failed'),errors:[code]});await setup();submit();await screen.findByText('Research report was not returned.');expect(screen.queryByText(/Research summary/)).toBeNull();expect(screen.queryByRole('table')).toBeNull();expect(screen.queryByRole('button',{name:'Open evidence C1'})).toBeNull();expect(screen.getByText(code)).toBeTruthy();expect(screen.getByText('Run ID: run-123')).toBeTruthy();expect(runResearchTask).toHaveBeenCalledTimes(1);},15000);
it.each(['network_error','backend_unavailable','timeout'])('transport %s keeps setup and never reruns',async code=>{runResearchTask.mockRejectedValue(new ApiClientError(code));await setup();submit();await screen.findByText(new ApiClientError(code).message);expect(screen.getByLabelText('Research Question').value).toBe('Compare methods');expect(runResearchTask).toHaveBeenCalledTimes(1);},15000);
it('new task clears selected Evidence and old report',async()=>{await setup();submit();await screen.findByText('Research Complete');fireEvent.click(screen.getAllByRole('button',{name:'Open evidence C1'})[0]);let resolve;runResearchTask.mockReturnValue(new Promise(r=>resolve=r));submit();expect(screen.queryByRole('complementary')).toBeNull();expect(screen.queryByRole('table')).toBeNull();await act(async()=>resolve(response()));},15000);
it('focus fetches newly ready papers without local injection',async()=>{let now=1000;vi.spyOn(Date,'now').mockImplementation(()=>now);await mount();libraryApi.documents.mockResolvedValue([...papers,{id:4,title:'New ready',status:'ready'}]);now=3000;fireEvent.focus(window);await choose('New ready');expect(libraryApi.documents).toHaveBeenCalledTimes(2);expect(screen.queryByText('Processing paper')).toBeNull();},15000);
it.each([2,3,4])('%s papers with long table text/title wrap safely and HTML remains text',async count=>{
 const style=document.createElement('style');style.textContent=readFileSync('src/styles.css','utf8');document.head.append(style);
 try{const data=response();data.citations[0].document_title='LongTitle'.repeat(100);data.report.comparison[1].value='<img src=x> '+ 'LongComparison'.repeat(200)+' [C2]';
 const extra=Array.from({length:count-2},(_,i)=>({id:i+4,title:`Extra paper ${i+4}`,status:'ready'}));libraryApi.documents.mockResolvedValue([...papers,...extra]);
 extra.forEach(p=>data.report.comparison.push({document_id:p.id,field:'method',value:'Available method',status:'supported'}));
 runResearchTask.mockResolvedValue(data);await setup();for(const p of extra)await choose(p.title);submit();await screen.findByText('Research Complete');const table=screen.getByRole('table');expect(within(table).getAllByRole('columnheader')).toHaveLength(count+1);expect(table.style.minWidth).toBe(`${180+count*240}px`);expect(table.querySelector('img')).toBeNull();expect(getComputedStyle(table.querySelector('td')).overflowWrap).toBe('anywhere');expect(getComputedStyle(table.querySelectorAll('th')[2]).overflowWrap).toBe('anywhere');expect(getComputedStyle(table.parentElement).overflowX).toBe('auto');fireEvent.click(within(table).getByRole('button',{name:'Open evidence C2'}));expect(getComputedStyle(screen.getByRole('complementary')).minWidth).toBe('0');}finally{style.remove();}
},20000);
